kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: logs-volume-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard
