apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.45.0-rc.0
          command: 
            - "/bin/sh"
            - "-c"
            - |
              cp /etc/prometheus/prometheus.yml /tmp/prometheus.yml
              sed -i "s/\PROMETHEUS_USERNAME/$PROMETHEUS_USERNAME/g" /tmp/prometheus.yml
              sed -i "s/\PROMETHEUS_PASSWORD/$PROMETHEUS_PASSWORD/g" /tmp/prometheus.yml
              sed -i 's#PROMETHEUS_REMOTE_WRITE_URL#'"$PROMETHEUS_REMOTE_WRITE_URL"'#g ' /tmp/prometheus.yml
              /bin/prometheus --config.file=/tmp/prometheus.yml \
                --storage.tsdb.path=/prometheus/ \
                --storage.tsdb.retention.time=28d \
                --web.enable-admin-api \
                --web.enable-lifecycle
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
          envFrom:
          - secretRef:
              name: observability-secrets
          resources:
            requests:
              cpu: 100m
              memory: 300Mi
            limits:
              cpu: 100m
              memory: 450M
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-config-map
