apm-server:
  ### Where apm will run
  host: "0.0.0.0:8200"
  rum:
    ### Tracks frontend to backend communication
    enabled: true
    allow_origins: ['*']
    library_pattern: "node_modules|bower_components|~"
    exclude_from_grouping: "^/webpack"
    source_mapping:
      enabled: true
      elasticsearch:
        hosts: ["localhost:9200"]
        username: "elastic"
        password: "changeme"
        expiration: 5m
      index_pattern: "apm-*-sourcemap*"
  kibana:
    enabled: true
    host: "kibana:5601"
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
